replicaCount: 1

image:
  repository: harbor.pyxis.dopolytech.fr/main/city-api
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

postgresql:
  auth:
    username: postgres
    password: postgres
    database: city_api
  primary:
    persistence:
      enabled: true
      size: 1Gi
    initdb:
      scriptsConfigMap: city-init-schema
