version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: city_api
    volumes:
      - postgres_data:/var/lib/postgresql/data
  go-web:
    build:
      context: go-web-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      CITY_API_ADDR: 0.0.0.0
      CITY_API_PORT: 8080
      CITY_API_DB_URL: db:5432/city_api
      CITY_API_DB_USER: postgres
      CITY_API_DB_PWD: postgres

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

volumes:
  postgres_data:
