apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      initContainers:
        - name: wait-for-db
          image: postgres:latest
          command: ['sh', '-c', 
            'until pg_isready -h {{ .Release.Name }}-postgresql:5432 -U {{ .Values.postgresql.postgresqlUsername }}; do echo waiting for database; sleep 2; done;']
      containers:
        - name: go-web-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: CITY_API_ADDR
              value: "0.0.0.0"
            - name: CITY_API_PORT
              value: "{{ .Values.service.port }}"
            - name: CITY_API_DB_URL
              value: "{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.postgresqlDatabase }}"
            - name: CITY_API_DB_USER
              value: "{{ .Values.postgresql.postgresqlUsername }}"
            - name: CITY_API_DB_PWD
              value: "{{ .Values.postgresql.postgresqlPassword }}"
