name: Release

on:
  push:
    tags: ['v*.*.*']

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log into registry
      run: echo '${{ secrets.REGISTRY_PASSWORD }}' | docker login ${{ secrets.REGISTRY_URL }} -u '${{ secrets.REGISTRY_USERNAME }}' --password-stdin

    - name: Pull and tag image
      run: |-
        docker pull '${{ secrets.REGISTRY_URL }}/city-api:${{ github.sha }}'
        
        # Create version tag from release tag (remove 'v' prefix)
        VERSION=$(echo '${{ github.ref_name }}' | sed 's/^v//')
        echo "Version: $VERSION"
        
        docker tag '${{ secrets.REGISTRY_URL }}/city-api:${{ github.sha }}' '${{ secrets.REGISTRY_URL }}/city-api:'$VERSION

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ secrets.REGISTRY_URL }}/city-api:${{ github.sha }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

    - name: Push Docker image
      run: docker push -a '${{ secrets.REGISTRY_URL }}/city-api'
